name: testing
 
on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      message:
        description: 'message to display'
        required: true
        default: 'hello world'
  schedule:
    - cron: "*/5 * * * *"
 
jobs:
  job1:
    name: a job 1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "${{github.event.inputs.message}}"
      - name: step 2
        run: |
          echo I insist: "${{github.event.inputs.message}}"