name: mail

on:
  workflow_dispatch:

jobs:
  job-email:
    name: send-email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Send mail with repository on Github Actions
          # Literal body:
          body: Hi Joan Marc,    Build job of ${{github.repository}} completed successfully!    Greatings, Sergi Diaz Lopez
          to: jmcarbo@imim.es
          bcc: dlopez2@imim.es
          from: Sergi Diaz Lopez # <user@example.com>
